accounts/urls.py
"""Defines URL patterns for accounts."""

from django.urls import path, include

from . import views


app_name = 'accounts'
urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),
    # Registration page.
    path('register/', views.register, name='register'),
]

imageGeneration/urls.py
'''Defines URL patterns for imageGeneration.'''

from django.urls import path

from . import views

app_name = 'imageGeneration'

urlpatterns = [
    # Prompts
    path('prompt/', views.prompt, name='prompt'),
    # Generated Images
    path('image/', views.image, name='image'),
]

learning_logs/urls.py
"""Defines URL patterns for learning_logs."""

from django.urls import path

from . import views

app_name = 'learning_logs'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # Page that shows all topics.
    path('generation/', views.generation, name='generation'),
    # Page that displays the generated images
    path('gallery/', views.gallery, name='gallery'),
    # Page that displays the user image generation history
    path('user_history/', views.user_history, name='user_history'),
    # Page to show the about us content
    path('about/', views.about, name='about'),
]

ll_project/urls.py
from django.contrib import admin
from django.urls import path, include

# Imported to display image files
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('imageGeneration/', include('imageGeneration.urls')),
    path('', include('learning_logs.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

imageGeneration/models.py
from django.db import models

# Create your models here.
class Prompt(models.Model):
    '''A prompt generated for the user'''
    text_field = models.TextField()  # Rename the field to avoid conflicts
    date_added = models.DateTimeField(auto_now_add=True)
    
    def get_text(self):
        return self.text_field
    
    def get_datetime(self):
        return self.date_added
    
    
class Image(models.Model):
    text_field = models.TextField()
    datetime_field = models.DateTimeField(auto_now_add=True)
    image_field = models.ImageField(upload_to='images/')

    def get_text(self):
        return self.text_field

    def get_datetime(self):
        return self.datetime_field

    def get_image_url(self):
        if self.image_field:
            return self.image_field.url
        return None
    

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


def register(request):
    """Register a new user."""
    if request.method != 'POST':
        # Display blank registration form.
        form = UserCreationForm()
    else:
        # Process completed form.
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Log the user in and then redirect to home page.
            login(request, new_user)
            return redirect('learning_logs:index')

    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'registration/register.html', context)

imageGeneration/views.py
from django.shortcuts import render
from .models import Prompt, Image
from django.contrib.auth.decorators import login_required


def prompt(request):
    '''Show all prompts'''
    prompt = Prompt.objects.all()
    context = {'prompt': prompt}
    return render(request, 'imageGeneration/prompt.html', context)


def image(request):
    '''Show all images'''
    image = Image.objects.all()
    context = {
        'image': image,
    }
    return render(request, 'imageGeneration/image.html', context)

learning_logs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404


def index(request):
    """The home page for Learning Log."""
    return render(request, 'learning_logs/index.html')

# Addition of imageForge Views

def generation(request):
    """Show generation page."""
    return render(request, 'learning_logs/generation.html')

def gallery(request):
    """Show gallery page."""
    return render(request, 'learning_logs/gallery.html')

def user_history(request):
    """Show user history page."""
    return render(request, 'learning_logs/user_history.html')

def about(request):
    """Show the about page."""
    return render(request, 'learning_logs/about.html')

imageGeneration/templates/imageGeneration/image.html
<!DOCTYPE html>
<html>
  <head>
    <title>Images</title>
  </head>
  <body>
    <h1>Images</h1>
    {% for image in image %}
    <div>
      <p>Added on: {{ image.get_datetime }}</p>
      <p>{{ image.get_text }}</p>
      <img src="{{ image.get_image_url }}" alt="Image" />
    </div>
    {% endfor %}
  </body>
</html>

imageGeneration/templates/imageGeneration/prompt.html
{% extends 'learning_logs/base.html' %} {% block page_header %}
<h1>User History</h1>
{% endblock page_header %} {% block content %}

<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  </head>
  <body>
    <h1>Prompts</h1>
    {% for prompt in prompt %}
    <div>
      <p>Added on: {{ prompt.get_datetime }}</p>
      <p>{{ prompt.get_text }}</p>
    </div>
    {% endfor %}
  </body>
</html>

{% endblock content %}

learning_logs/templates/learning_logs/about.html
{% extends 'learning_logs/base.html' %} {% block page_header %}
<h1>About Us</h1>
{% endblock page_header %} {% block content %}
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <div class="card mb-3" style="height: 30vh">
        <div class="card-body d-flex align-items-center justify-content-center">
          <div
            class="border border-secondary rounded p-3 text-center"
            style="width: 100%; height: 100%"
          >
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            Suspendisse rhoncus dapibus arcu, non tempus ligula aliquet eu.
            Vivamus scelerisque est in velit sagittis, vel dignissim turpis
            varius. Nullam ultrices, nunc nec mattis accumsan, ipsum nibh
            tempus metus, in varius turpis magna at velit. Aenean semper
            semper felis, et consectetur risus ullamcorper sed. Donec id neque
            urna. Cras a diam a mi auctor venenatis. Fusce tincidunt, mi in
            efficitur rhoncus, nisi risus auctor nisi, sit amet faucibus ipsum
            neque sed urna.
          </p>
      </br>
      <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit.
          Suspendisse rhoncus dapibus arcu, non tempus ligula aliquet eu.
          Vivamus scelerisque est in velit sagittis, vel dignissim turpis
          varius. Nullam ultrices, nunc nec mattis accumsan, ipsum nibh
          tempus metus, in varius turpis magna at velit. Aenean semper
          semper felis, et consectetur risus ullamcorper sed. Donec id neque
          urna. Cras a diam a mi auctor venenatis. Fusce tincidunt, mi in
          efficitur rhoncus, nisi risus auctor nisi, sit amet faucibus ipsum
          neque sed urna.
        </p>
          </div>
        </div>
      </div>
      <div class="mt-4"></div>
      <!-- 20% gap between boxes -->
      <div class="card" style="height: 30vh">
        <div class="card-body d-flex align-items-center justify-content-center">
          <div
            class="border border-secondary rounded p-3 text-center"
            style="width: 100%; height: 100%"
          >
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit.
              Suspendisse rhoncus dapibus arcu, non tempus ligula aliquet eu.
              Vivamus scelerisque est in velit sagittis, vel dignissim turpis
              varius. Nullam ultrices, nunc nec mattis accumsan, ipsum nibh
              tempus metus, in varius turpis magna at velit. Aenean semper
              semper felis, et consectetur risus ullamcorper sed. Donec id neque
              urna. Cras a diam a mi auctor venenatis. Fusce tincidunt, mi in
              efficitur rhoncus, nisi risus auctor nisi, sit amet faucibus ipsum
              neque sed urna.
            </p>
        </br>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            Suspendisse rhoncus dapibus arcu, non tempus ligula aliquet eu.
            Vivamus scelerisque est in velit sagittis, vel dignissim turpis
            varius. Nullam ultrices, nunc nec mattis accumsan, ipsum nibh
            tempus metus, in varius turpis magna at velit. Aenean semper
            semper felis, et consectetur risus ullamcorper sed. Donec id neque
            urna. Cras a diam a mi auctor venenatis. Fusce tincidunt, mi in
            efficitur rhoncus, nisi risus auctor nisi, sit amet faucibus ipsum
            neque sed urna.
          </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

learning_logs/templates/learning_logs/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>imageForge</title>

    {% load django_bootstrap5 %} {% bootstrap_css %} {% bootstrap_javascript %}
    {% load static %}
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
    />
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'learning_logs:index' %}">
          imageForge</a
        >

        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarCollapse"
          aria-controls="navbarCollapse"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul
            class="navbar-nav me-auto mb-2 mb-md-0 navbar-nav d-flex justify-content-evenly w-100"
          >
            <li class="nav-item">
              <a class="nav-link" href="{% url 'learning_logs:generation' %}">
                Generation</a
              >
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'imageGeneration:image' %}">
                Gallery</a
              >
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'imageGeneration:prompt' %}">
                User History</a
              >
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'learning_logs:about' %}">
                About</a
              >
            </li>
          </ul>
          <!-- End of links on left side of navbar -->

          <!-- Account-related links -->
          <ul class="navbar-nav ms-auto mb-2 mb-md-0">
            {% if user.is_authenticated %}
            <li class="nav-item">
              <span class="navbar-text me-2">Hello, {{ user.username }}. </span>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:register' %}">
                Register</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:login' %}"> Log in</a>
            </li>
            {% endif %}
          </ul>
          <!-- End of account-related links -->

          {% if user.is_authenticated %}
          <form action="{% url 'accounts:logout' %}" method="post">
            {% csrf_token %}
            <button name="submit" class="btn btn-outline-secondary btn-sm">
              Log out
            </button>
          </form>
          {% endif %}
        </div>
        <!-- Closes collapsible parts of navbar -->
      </div>
      <!-- Closes navbar's container -->
    </nav>
    <!-- End of navbar -->

    <main class="container">
      <div class="pb-2 mb-2 border-bottom">
        {% block page_header %}{% endblock page_header %}
      </div>

      <div>{% block content %}{% endblock content %}</div>
    </main>
    <footer class="bg-dark text-white py-3 fixed-bottom">
      <div class="container">
        <div class="row">
          <div class="col-md-6">
            <div class="d-flex justify-content-start">
              <a href="#" class="btn btn-outline-light me-2">
                <i
                  class="fab fa-github-square social-icon fa-2x"
                  aria-hidden="true"
                ></i>
              </a>
              <a href="#" class="btn btn-outline-light me-2">
                <i
                  class="fab fa-linkedin social-icon fa-2x"
                  aria-hidden="true"
                ></i>
              </a>
              <a href="#" class="btn btn-outline-light me-2">
                <i
                  class="fab fa-twitter-square social-icon fa-2x"
                  aria-hidden="true"
                ></i>
              </a>
              <a href="#" class="btn btn-outline-light me-2">
                <i
                  class="fab fa-instagram social-icon fa-2x"
                  aria-hidden="true"
                ></i>
              </a>
            </div>
          </div>
          <div class="col-md-6">
            <div class="d-flex justify-content-end">
              <a href="#" class="btn btn-primary subscribe-btn">Subscribe</a>
            </div>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}

  <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

  <p>Edit entry:</p>

  <form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_div }}
    <button name="submit">Save changes</button>
  </form>

{% endblock content %}

learning_logs/templates/learning_logs/gallery.html
{% extends 'learning_logs/base.html' %} {% block page_header %}
<h1>Gallery</h1>
{% endblock page_header %} {% block content %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <p>This is the gallery page</p>
  </body>
</html>

{% endblock content %}

learning_logs/templates/learning_logs/generation.html
{% extends 'learning_logs/base.html' %} {% block page_header %}
<h1>Generation</h1>
{% endblock page_header %} {% block content %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <p>This is taking the place of the image generation command</p>
  </body>
</html>

{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends 'learning_logs/base.html' %} {% block page_header %}
<div class="p-3 mb-4 bg-light border rounded-3">
  <div class="container-fluid py-4">
    <h1 class="display-3">Welcome to imageForge!</h1>

    <p class="lead">
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam malesuada
      massa nec orci volutpat, non luctus lacus efficitur. Ut vitae nunc velit.
      Nam vulputate pellentesque leo, vel pharetra neque eleifend at. Mauris ac
      dolor ut metus convallis luctus. Nunc finibus orci ipsum, id bibendum
      lacus posuere in. Vestibulum at justo felis. Fusce eget enim nec est
      aliquam dignissim a a ligula. Integer id ipsum turpis.
    </p>

    <a class="btn btn-primary btn-lg mt-1" href="{% url 'accounts:register' %}"
      >Register &raquo;</a
    >
  </div>
</div>

<div
  class="d-flex justify-content-center align-items-center"
  style="height: 20vh"
>
  <form method="POST" action="{% url 'learning_logs:generation' %}">
    {% csrf_token %}
    <button type="submit" class="btn btn-success btn-lg mt-1">GENERATE</button>
  </form>
</div>
{% endblock page_header %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}

  <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

  <p>Add a new entry:</p>
  <form action="{% url 'learning_logs:new_entry' topic.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_div }}
    <button name='submit'>Add entry</button>
  </form>

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}

{% block content %}
  <p>Add a new topic:</p>

  <form action="{% url 'learning_logs:new_topic' %}" method='post'>
    {% csrf_token %}
    {{ form.as_div }}
    <button name="submit">Add topic</button>
  </form>

{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block page_header %}
  <h1>{{ topic.text }}</h1>
{% endblock page_header %}

{% block content %}

  <p>
    <a href="{% url 'learning_logs:new_entry' topic.id %}">Add new entry</a>
  </p>

  {% for entry in entries %}
    <div class="card mb-3">
      <!-- Card header with timestamp and edit link -->
      <h4 class="card-header">
        {{ entry.date_added|date:'M d, Y H:i' }}
        <small><a href="{% url 'learning_logs:edit_entry' entry.id %}">
          edit entry</a></small>
      </h4>
      <!-- Card body with entry text -->
      <div class="card-body">{{ entry.text|linebreaks }}</div>
    </div>
  {% empty %}
    <p>There are no entries for this topic yet.</p>
  {% endfor %}

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends 'learning_logs/base.html' %}

{% block page_header %}
  <h1>Topics</h1>
{% endblock page_header %}

{% block content %}

  <ul class="list-group border-bottom pb-2 mb-4">
    {% for topic in topics %}
      <li class="list-group-item border-0">
        <a href="{% url 'learning_logs:topic' topic.id %}">
          {{ topic.text }}</a>
      </li>
    {% empty %}
      <li class="list-group-item border-0">No topics have been added yet.</li>
    {% endfor %}
  </ul>

  <a href="{% url 'learning_logs:new_topic' %}">Add a new topic</a>

{% endblock content %}

learning_logs/templates/learning_logs/user_history.html
{% extends 'learning_logs/base.html' %} {% block page_header %}
<h1>User History</h1>
{% endblock page_header %} {% block content %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <p>This is the user history page</p>
  </body>
</html>

{% endblock content %}